# Generated by Django 5.2.6 on 2025-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('desription', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
